language: node_js
node_js: 12
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run is-es5
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run coveralls
env:
  global:
    # NPM_TOKEN
    - secure: vNrUQ9CbEPce1FQJHJJNEJJrG98CYUsIcoCDkd7wYVf7y8RKRMTbe3X22SMzphiR0dcytogeBT5E06W8xV6lSC0DA/W0ggRJUvkXsoWtYkDkECCfjvILorWDkfZafYPJbFI5BHoNPDTp7Ayde1z4QAdwrtDcPZjrwszzbcN4T91oJFC8nOLcSQIm/I1C0MP5yTuAkwemUbQjStzLdwZ7JOOUbELj4/zaheKDewBscvTWibAHQTYGbKzJ9l6CsFAcqkpLb9npRdvaY8LVlMqy+nE+llVp41FtYcm3oaHd4D91i3e7OTuxMSBZKw1FcrNgMUCr1xMPGH0sEinhiGvDjA2XrBNKdz1K1PBetmLb0DLlSIIJkIo1JbcrIUSQzEq7X+dG7qGO3etaQ+jtFa84wIEqfMNrTFQpOPFtwUF1dPgLrw9/eKB1vjo9EnpUPwbKwhsppwAdfIOJnVzfo+yyHoOeWCsuWfO8NGlXgScchbBWOzIs3zM9lZK3qgpNNqU9nSKoXL1cBu6jvpPVwjnxTd95ujPgC+1awHtiYqMxsfBjf/uCNtWZG3cnWFZJSCD9vXB3l/C7JjKHvjyD/PdcD3q64vFH6RXeL3MVahca1e6iC2WntgrUQqtKpbY7FApPD23mknBU4dizqaKoAU1h0SQZYvaKi52FTHCg4lItXBY=
    # GH_TOKEN
    - secure: Ix/cBLgrd6/NXVgYUY91UIPzTdshxlxw15WmZhdFA40LmcOPmAjA4F0tDLJUZDLz6jlRhtnrvT5wIpCMMzCt5Ur3s7XNJH1dFfD3j0zhT+tw9oXzQVbmINQcYKceczqeL6LfKH6eRAobt9Xx4/lHHDjMtY53qZeLmX768X02nJKxy+NplvJ+5AWw1wPhLo7TW62BJMVeN9yBg8AVbV3597oJbcoQY89D8DwY80arxfxB7ZFO5to5v4+5c/tvflKCzl3ABqauNL57UmRyaFSvpEOka1fP7RJPfHkRMxaH+TqnggZidYvDqQpjZXnw0WVBPGewfG/3ffl6GCU4QbsGTBtxSG1viTk22OVtfC16TVE6dFfEWlY5OZdi+nKaQCZb7UmEC1j8o3NZbB5GCmVrrfV97I756TSzyfY9rUz8gpbD+mC/ZU98gJmFDOc6HDt/pRt3aYdB4M4HyU5xvrjzO6Upes1XaXSjYrzLJvtGF31YsnpClQIyzdH07ZAKdABBxQIvlg4Djf9aKYbZBIyqV4lQtVsD9HoA5WRaipuhq8YIKAalRFdz+Omx8XQt0hlem3dPOw5Fm7jHspq9vwt4dXVRLBhMpAXeejW2l9d1nnbkxjJDCKvqHAVAidMlbPBH89TFya6iVPb4l/DSUY8r4OdRHJeqPbtOLtbw82xyy2I=
